spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
