version: '3.7'
networks:
  sentinel:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=doemvnf
    networks:
      - sentinel
    ports:
      - '6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=doemvnf
      - REDIS_PASSWORD=doemvnf
    ports:
      - '6479:6379'
    depends_on:
      - redis
    networks:
      - sentinel
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_SET=admaster
      - REDIS_MASTER_PASSWORD=doemvnf
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      - sentinel

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
